name: barberly
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.3

  # Navigation
  go_router: ^17.2.0
  cupertino_icons: ^1.0.8
  
  # Geolocalización y Mapas
    # Consultas por radio en Firestore usando geohashes
  geoflutterfire_plus: ^0.0.34
  # Acceso al GPS del dispositivo con gestión de permisos
  geolocator: ^13.0.2
  # Mapa interactivo OpenStreetMap
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  google_sign_in: ^6.2.2
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
