// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsPo5WL5uNqHSF44BiMfy-9e6vXEWG510',
    appId: '1:566264148896:android:a3fa41b4dfef10f4992ac5',
    messagingSenderId: '566264148896',
    projectId: 'barberly-dev-6aef2',
    storageBucket: 'barberly-dev-6aef2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk_q09p2b_-BCo-1jGCQQrt_L1z57kSCU',
    appId: '1:566264148896:ios:5b5135270172a253992ac5',
    messagingSenderId: '566264148896',
    projectId: 'barberly-dev-6aef2',
    storageBucket: 'barberly-dev-6aef2.firebasestorage.app',
    iosBundleId: 'com.example.barberly',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa0J5mCRDysAn3xCqSuC1DcCeFgdD5Z3U',
    appId: '1:566264148896:web:0ef19f84c7dbcc79992ac5',
    messagingSenderId: '566264148896',
    projectId: 'barberly-dev-6aef2',
    authDomain: 'barberly-dev-6aef2.firebaseapp.com',
    storageBucket: 'barberly-dev-6aef2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk_q09p2b_-BCo-1jGCQQrt_L1z57kSCU',
    appId: '1:566264148896:ios:5b5135270172a253992ac5',
    messagingSenderId: '566264148896',
    projectId: 'barberly-dev-6aef2',
    storageBucket: 'barberly-dev-6aef2.firebasestorage.app',
    iosBundleId: 'com.example.barberly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa0J5mCRDysAn3xCqSuC1DcCeFgdD5Z3U',
    appId: '1:566264148896:web:4d8f920146dfa4cc992ac5',
    messagingSenderId: '566264148896',
    projectId: 'barberly-dev-6aef2',
    authDomain: 'barberly-dev-6aef2.firebaseapp.com',
    storageBucket: 'barberly-dev-6aef2.firebasestorage.app',
  );

}